#!/bin/zsh

set -o pipefail;


# make_vivaldi_profile
function make_vivaldi_profile() {
  rm ~/library/roboczy/app-data/vivaldi/profile-26*.7z
  local ts;
  ts=$(date --iso-8601 | cut -c3,4,6,7,9,10);
  7z a -t7z ~/library/roboczy/app-data/vivaldi/profile-"$ts".7z ~/.config/vivaldi/Default
  unset ts;
}


# make_vnstat_database
function make_vnstat_database() {
  local ts;
  ts=$(date --iso-8601 | cut -c3,4,6,7,9,10)
  7z a -ttar ~/library/roboczy/app-data/vnstat/cachyos-netuse-"$ts".tar /var/lib/vnstat/vnstat.db /etc/vnstat.conf
  unset ts
}


# make_thunderbird_profile loolnehx.default-release
function make_thunderbird_profile() {
  rm ~/library/roboczy/app-data/thunderbird/profile-26*.7z
  local -r tid="$1";
  local -r ts=$(date --iso-8601 | cut -c3,4,6,7,9,10);
  7z a -t7z ~/library/roboczy/app-data/thunderbird/profile-"$ts".7z ~/.thunderbird/"$tid"
}


# rsync -vrhupXgolt --del --dry-run ~/library/roboczy/ /run/media/$USER/crucial-backup/backup-data/roboczy/ | less
# rsync -vrhupXgolt --del --progress ~/library/roboczy/ /run/media/$USER/crucial-backup/backup-data/roboczy/
function copy_data() {
  local device="$1"
  local dir="$2";
  local options="$3";
  local source=~/library/"$dir"/;
  local target=/run/media/$USER/"$device"/"$dir"/;

  echo "[$0] source = $source";
  echo "[$0] target = $target";
  echo "[$0] status = $(file -b "$source")";
  echo "[$0] status = $(file -b "$target")";

  echo -n "[$0] continue? [enter ctrl+c] ";
  read -r;

  rsync -vrhptgolu --del --dry-run "$source" "$target" | less
  echo -n "[$0] continue? [yn] ";
  read -r;
  local choice="${REPLY:0:1}";

  if [[ $choice == y ]]; then 
    echo "[$0] if-branch = yes";
    echo -n "[$0] continue? [enter ctrl+c]";
    if [ -z "$options" ]; then rsync -vrhupXgolt --del "$source" "$target";
    else rsync -vrhupXgolt --del "$options" "$source" "$target";
    fi
  else 
    echo "[$0] if-branch = no";
  fi
}


# copy_data_with_progress crucial-backup/backup-data roboczy
# copy_data_with_progress crucial-backup/backup-data software
# copy_data crucial-backup/backup-data archive
# copy_data crucial-backup/backup-data documents
# copy_data crucial-backup/backup-data images
# copy_data crucial-backup/backup-data music
# copy_data crucial-backup/backup-data projects

# copy_data_with_progress backup-hdd/backup-data roboczy
# copy_data_with_progress backup-hdd/backup-data software
# copy_data backup-hdd/backup-data archive
# copy_data backup-hdd/backup-data documents
# copy_data backup-hdd/backup-data images
# copy_data backup-hdd/backup-data music
# copy_data backup-hdd/backup-data projects
function copy_data_with_progress() {
  copy_data "$1" "$2" "--progress";
}


# try_to_copy_data ~/library/roboczy "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/software "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/archive "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/documents "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/images "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/music "/run/media/$USER/crucial-backup/backup-data/"
# try_to_copy_data ~/library/projects "/run/media/$USER/crucial-backup/backup-data/"

# try_to_copy_data ~/library/roboczy "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/software "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/archive "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/documents "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/images "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/music "/run/media/$USER/backup-hdd/backup-data/"
# try_to_copy_data ~/library/projects "/run/media/$USER/backup-hdd/backup-data/"
function try_to_copy_data() {
  local -r source="$1"
  local -r target="$2";
  
  local -r err_source_dir_not_found=1;
  local -r err_target_dir_not_found=2;
  local -r ret_choose_to_quit=3;
  local -r ret_choose_to_not_continue=4;

  echo "[$0] source: $source";
  echo "[$0] target: $target";

  if [ ! -d "$target" ]; then
    print -u2 "[$0] $(file -b "$target")";
    return $err_target_dir_not_found;
  elif [ ! -d "$source" ]; then
    print -u2 "[$0] $(file -b "$source")";
    return $err_source_dir_not_found;
  fi
  
  echo -n "[$0] continue? [enter q] ";
  read -r;
  local choice="${REPLY:0:1}";
  if [[ $choice == q ]]; then
    echo "[$0] q: ret_choose_to_quit";
    return $ret_choose_to_quit;
  fi

  rsync -vrhupXgolt --del --dry-run "$source" "$target" | less;
  echo -n "[$0] continue? [ypn] ";
  read -r;
  choice="${REPLY:0:1}";

  if [[ $choice == y ]]; then
    echo "[$0] y: -vrhupXgolt --del";
    rsync -vrhupXgolt --del "$source" "$target";
  elif [[ $choice == p ]]; then
    echo "[$0] p: --progress";
    rsync -vrhupXgolt --del --progress "$source" "$target";
  elif [[ $choice == n ]]; then
    echo "[$0] n: ret_choose_to_not_continue";
    return $ret_choose_to_not_continue;
  fi
  
  return 0;
}


# try_to_copy_all_data_to_disk crucial-backup/backup-data
# try_to_copy_all_data_to_disk backup-hdd/backup-data
function try_to_copy_all_data_to_disk() {
  local -r device_and_dir="$1";
  local -r target="/run/media/$USER/$device_and_dir/";
  local -r err_dir_not_specified=1;
  local -r err_target_dir_not_exists=2;
  
  if [[ -z "$device_and_dir" ]]; then
    print -u2 "[$0] device+directory not specified";
    return $err_dir_not_specified;
  fi
  if [ ! -d "$target" ]; then
    print -u2 "[$0] target='$target' directory is missing";
    return $err_target_dir_not_exists;
  fi
  
  rsync -vrhupXgolt --del ~/library/roboczy "$target";
  rsync -vrhupXgolt --del ~/library/software "$target";
  rsync -vrhupXgolt --del ~/library/archive "$target";
  rsync -vrhupXgolt --del ~/library/documents "$target";
  rsync -vrhupXgolt --del ~/library/images "$target";
  rsync -vrhupXgolt --del ~/library/music "$target";
  rsync -vrhupXgolt --del ~/library/projects "$target";
}


# make_block_copy_of_cachyos /run/media/$USER/crucial-backup/cachyos-img
# make_block_copy_of_cachyos "/run/media/$USER/backup-hdd/cachyos-img"
function make_block_copy_of_cachyos() {
  local -r target="$1"
  local -r err_dir_not_found=1;

  if [ ! -d "$target" ]; then
    echo "[$0] directory not found";
    file "$target";
    return $err_dir_not_found;
  fi
  
  rm -v "$target"/limine-boot.img
  sudo dd if=/dev/nvme0n1p1 of="$target"/limine-boot.img status=progress
  sudo chown "$USER" "$target"/limine-boot.img
  file "$target"/limine-boot.img
  echo;
  
  rm -v "$target"/cachyos-root.img
  sudo dd if=/dev/nvme0n1p2 of="$target"/cachyos-root.img status=progress
  sudo chown "$USER" "$target"/cachyos-root.img
  file "$target"/cachyos-root.img
  echo;
}


# make_compressed_block_copy_of_cachyos /run/media/$USER/games/cachyos-img-bz2
function make_compressed_block_copy_of_cachyos() {
  local -r target="$1";
  local -r err_dir_not_found=1;

  if [ ! -d "$target" ]; then
    echo "[$0] directory not found";
    file "$target";
    return $err_dir_not_found;
  fi
  
  {
    echo "❯ lsblk";
    lsblk | grep -vE 'sda|zram';
    echo;
    echo "❯ lsblk --fs"; 
    lsblk --fs | grep -vE 'sda|zram'; 
    echo;
    echo "❯ df -h";      
    df -h | grep -i 'nvme';
    echo;
  } > "$target"/info.txt
  
  sudo dd if=/dev/nvme0n1p1 status=progress | bzip2 > "$target"/limine-boot.bz2
  sudo dd if=/dev/nvme0n1p2 status=progress | bzip2 > "$target"/cachyos-root.bz2
}


# report_backup_storage wd-hdd
# report_backup_storage backup-hdd
# report_backup_storage crucial-backup
function report_backup_storage() {
  local -r device_path="$1";
  local -r source="/run/media/$USER/$device_path";
  local -r target="/home/$USER/library/roboczy/app-data/rsync";
  local -r err_choice_not_yes=1;
  local -r err_dir_source_missing=2;

  echo "[$0] source = $source";
  echo "[$0] target = $target";
  echo "[$0] status = $(file -b "$source")";
  echo "[$0] status = $(file -b "$target")";
  echo -n "[$0] continue? [yn] ";
  read -r;
  local -r choice="${REPLY:0:1}";

  if [[ $choice != y ]]; then
    print -u2 "[$0] choice != y";
    return $err_choice_not_yes;
  fi
  
  if [ -d "$source" ]; then
    local -r current_date=$(date -I | cut -c1-4,6-7,9-10);
    local -r current_time=$(date +%H-%M | cut -c1-2,4-5);
    local -r prefix="$device_path";
    local -r filename="$target"/"$prefix"-"$current_date"-"$current_time";
    ls -lhSFR "$source" > "$filename";
    echo >> "$filename"
    {
      echo; lsblk --fs;
      echo; lsblk;
      echo;
    } >> "$filename"
    echo "[$0] filename = '$filename'";
  else
    print -u2 "[$0] target device is missing";
    return $err_dir_source_missing;
  fi

  return 0;
}

