#!/bin/zsh


# trim_str "  aaa bbb \n"
function trim_str() {
  local var="$1";
  local trim=${${var%${var##*[^[:blank:]]}}#${${var%${var##*[^[:blank:]]}}%%[^[:blank:]]*}};
  echo "$trim";
}


# to_lowercase AAA
function to_lowercase() {
  local text="$1";
  echo ${(L)text};
}


function str_between_2() {
  local result;
  result=$(print "$1" | grep -o -P "(?<=$2).*(?=$3)");
  stdout "$result";
}


# generate_unsorted_list "https://www.nexusmods.com/hitman3/mods/200 | simple mod framework\nhttps://www.nexusmods.com/hitman3/mods/784 | hitman world of assassination unofficial community patch"
# str=$(cat ~/library/documents/db/recenzje/hitman-woa | head -38 | tail +26) && generate_unsorted_list "$str";
function generate_unsorted_list() {
  local output="<ul>\n";
  local n_lines=$(echo "$1" | wc -l);
  local lines=();

  for ((i=1; i <= $n_lines; i++)); do
    local entry=$(echo "$1" | cut -d $'\n' -f"$i");
    
    local url=$(echo "$entry" | cut -d\| -f1);
    local desc=$(echo "$entry" | cut -d\| -f2);
    url=$(trim_str "$url");
    desc=$(trim_str "$desc");
    
    output+="\t<li><a href=\""$url"\">"$desc"</a></li>\n";
  done
  
  output+="</ul>";
  echo "$output";
}


# generate_soundtrack_table "--- hitman 1\nhttps://www.youtube.com/watch?v=9b-nHWlD0C4 | e3 2015 announcement trailer song | 6m6s\nhttps://www.youtube.com/watch?v=2Vg05bVsT-A | legacy opening cinematic | 2m18s"
function generate_soundtrack_table() {
  local output="<table class=\"soundtrack-ost\">\n";
  local n_lines=$(echo "$1" | wc -l);
  local lines=();

  local entry=$(echo "$1" | cut -d $'\n' -f1);
  if [[ $(echo "$entry" | cut -c1-4) == "--- " ]]; then
    local text=$(echo "$entry" | cut -c5-);
    output+="\t<caption>$text</caption>\n";
    output+="\t<tr>\n\t\t<td class=\"soundtrack-ost--name\"></td>\n\t\t<td></td>\n\t</tr>\n";
  fi
      
  for ((i=2; i <= $n_lines; i++)); do
    local entry=$(echo "$1" | cut -d $'\n' -f"$i");

    local url=$(echo "$entry" | cut -d\| -f1);
    local desc=$(echo "$entry" | cut -d\| -f2);
    local dur=$(echo "$entry" | cut -d\| -f3);
    url=$(trim_str "$url");
    desc=$(trim_str "$desc");
    dur=$(trim_str "$dur");
    
    local min=$(echo "$dur" | grep -o '^[0-9]*[m$]' | tr 'm' ':');
    local sec=$(echo "$dur" | grep -o '[^m][0-9]*[s$]');
    if [[ $#sec == 2 ]]; then
      sec="0$sec";
    fi
    sec="${sec:0:-1}";
    local duration="$min$sec";

    output+="\t<tr>\n\t\t<td><a href=\"$url\">$desc</a></td>\n\t\t<td>$duration</td>\n\t</tr>\n";
  done
  
  output+="</table>";
  echo "$output";
}


# str=$(cat ~/library/documents/db/recenzje/"251116 freshwomen season 2" | awk 'NR>=211 && NR<=230') && generate_soundtrack_table_assuming_timer_duration "$str";
function generate_soundtrack_table_assuming_timer_duration() {
  local output="<table class=\"soundtrack-ost\">\n";
  local n_lines=$(echo "$1" | wc -l);
  local lines=();

  local entry=$(echo "$1" | cut -d $'\n' -f1);
  if [[ $(echo "$entry" | cut -c1-4) == "--- " ]]; then
    local text=$(echo "$entry" | cut -c5-);
    output+="\t<caption>$text</caption>\n";
    output+="\t<colgroup>\n\t\t<col span="1" class=\"soundtrack-ost--name\">\n\t</colgroup>\n";
  fi
    
  local name;
  local author;  
  for ((i=2; i <= $n_lines; i++)); do
    local entry=$(echo "$1" | cut -d $'\n' -f"$i");

    local url=$(echo "$entry" | cut -d\| -f1);
    local desc=$(echo "$entry" | cut -d\| -f2);
    local dur=$(echo "$entry" | cut -d\| -f3);
    url=$(trim_str "$url");
    desc=$(trim_str "$desc");
    dur=$(trim_str "$dur");
    
    name=$(str_between_2 "$desc" '^' " –");
    author=$(str_between_2 "$desc" " –" '$');

    output+="\t<tr>\n\t\t<td><a href=\"$url\">$name</a> – $author</td>\n\t\t<td>$dur</td>\n\t</tr>\n";
  done
  
  output+="</table>";
  echo "$output";
}


# generate_achievements_table "--- base game\nUnseen Assassin | Assassinate a Target without getting spotted.\nSilent Sniper | Complete The Last Yardbird as Silent Assassin. | https://www.youtube.com/watch?v=OedhC3F7UR4"
# str=`awk 'NR>=1235 && NR<=1246' ~/library/documents/db/recenzje/hitman-woa`; generate_achievements_table "$str";
function generate_achievements_table() {
  local output="<table class=\"achievements\">\n";
  local n_lines=$(echo "$1" | wc -l);
  local lines=();

  local entry=$(echo "$1" | cut -d $'\n' -f1);
  if [[ $(echo "$entry" | cut -c1-4) == "--- " ]]; then
    local text=$(echo "$entry" | cut -c5-);
    text=$(to_lowercase "$text");
    output+="\t<caption>$text</caption>\n";
    output+="\t<tr>\n\t\t<td class=\"achievements--name\"></td>\n\t\t<td></td>\n\t</tr>\n";
  fi
      
  for ((i=2; i <= $n_lines; i++)); do
    local entry=$(echo "$1" | cut -d $'\n' -f"$i");

    local name=$(echo "$entry" | cut -d\| -f1);
    local desc=$(echo "$entry" | cut -d\| -f2);
    local url=$(echo "$entry" | cut -d\| -f3);
    name=$(trim_str "$name");
    desc=$(trim_str "$desc");
    name=$(to_lowercase "$name");
    desc=$(to_lowercase "$desc");
    
    if [ -n "$url" ]; then
      url=$(trim_str "$url");
      output+="\t<tr>\n\t\t<td><a href=\"$url\">$name</a></td>\n\t\t<td>$desc</td>\n\t</tr>\n";
    else
      output+="\t<tr>\n\t\t<td>$name</td>\n\t\t<td>$desc</td>\n\t</tr>\n";
    fi
  done
  
  output+="</table>\n<br>\n";
  echo "$output";
}

# generate_escalations_entry "2016-03-22\nthe gemini fiasco\nhttps://www.youtube.com/watch?v=G3NDdBtG96M | 0:52, 2:22, 2:24, 2:23, 2:27\nhttps://www.youtube.com/watch?v=Pf-MoKhiL9A | 1 | 2:42\nhttps://www.youtube.com/watch?v=J9XYM6-FFuI | 2 | 4:50\nhttps://www.youtube.com/watch?v=-sDw-mqAi-Q | 3 | 4:46\nhttps://www.youtube.com/watch?v=L-GVXwPxseg | 4 | 4:57\nhttps://www.youtube.com/watch?v=_GCWMeP_qJY | 5 | 8:41"
# generate_escalations_entry "2016-03-29\nthe einarsson inception\nhttps://www.youtube.com/watch?v=YkibnfhQq18 | 1:06, 1:07, 1:43, 1:40, 1:41\nhttps://www.youtube.com/watch?v=psfZ4B8lgQM | 1 | 1:13\nhttps://www.youtube.com/watch?v=fCat3BfYMug | 2 | 1:26\nhttps://www.youtube.com/watch?v=ZtAwPj_fgQU | 3 | 2:45\nhttps://www.youtube.com/watch?v=9hlA6Wga6l8 | 4 | 2:46\nhttps://www.youtube.com/watch?v=D9EcA5RODtI | 5 | 0:52\nhttps://www.youtube.com/watch?v=9-i-FAtNF80 | 5 | 1:14"
# str=$(awk 'NR>=555 && NR<=562' ~/library/documents/db/recenzje/hitman-woa); generate_escalations_entry "$str";
function generate_escalations_entry() {
  local -r n_lines=$(echo "$1" | wc -l);
  local output="<tr>\n";
  
  local date_=$(echo "$1" | cut -d $'\n' -f1);
  local name=$(echo "$1" | cut -d $'\n' -f2);  
  local all_levels=$(echo "$1" | cut -d $'\n' -f3);
  local main_url=$(echo "$all_levels" | cut -d\| -f1);
  local main_durations=$(echo "$all_levels" | cut -d\| -f2);
  date_=$(trim_str "$date_");
  name=$(trim_str "$name");
  main_url=$(trim_str "$main_url");
  main_durations=$(trim_str "$main_durations");
  output+="\t<td>$date_</td>\n";
  output+="\t<td><a href=\"$main_url\">$name</a></td>\n";
  output+="\t<td>$main_durations</td>\n";
  
  local td="\t<td>\n";
  for ((i=4; i <= $n_lines; i++)); do
    local entry=$(echo "$1" | cut -d $'\n' -f"$i");
    local url=$(echo "$entry" | cut -d\| -f1);
    local level=$(echo "$entry" | cut -d\| -f2);
    local duration=$(echo "$entry" | cut -d\| -f3);
    url=$(trim_str "$url");
    level=$(trim_str "$level");
    duration=$(trim_str "$duration");
    td+="\t\t<a href=\"$url\">$duration</a>, \n";
  done
  
  td=${td:0:-4}'\n';
  td+="\t</td>\n";
  output+="$td";
  output+="</tr>\n";
  echo "$output";
}


